import { useState, useEffect } from 'react';
import './CategorySelect.css';
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';
interface Props {
  players: string[];
  onWordsReady: (words: string[], category: string) => void;
}

type Status = 'idle' | 'loading' | 'error';

export default function CategorySelect({ players, onWordsReady }: Props) {
  const [category, setCategory] = useState('');
  const [status, setStatus] = useState<Status>('idle');
  const [errorMsg, setErrorMsg] = useState('');
  const [source, setSource] = useState<'gemini' | 'database' | null>(null);
  const [cachedCategories, setCachedCategories] = useState<string[]>([]);

  useEffect(() => {
    fetch(`${API_URL}/api/category`)
      .then(r => r.json())
      .then(data => { if (Array.isArray(data)) setCachedCategories(data); })
      .catch(() => {});
  }, []);

  const handleGenerate = async () => {
    const trimmed = category.trim();
    if (!trimmed) return;
    setStatus('loading');
    setErrorMsg('');
    setSource(null);
    try {
      const res = await fetch(`${API_URL}/api/category`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ category: trimmed }),
      });
      if (!res.ok) throw new Error('Server error');
      const data = await res.json();
      setSource(data.source);
      setTimeout(() => onWordsReady(data.words, trimmed), 900);
    } catch {
      setStatus('error');
      setErrorMsg('Could not connect to server. Is your backend running?');
    }
  };

  const isLoading = status === 'loading';

  return (
    <div className="cs-bg">
      <div className="cs-blob" style={{ width: 350, height: 350, background: '#7b2ff7', top: -80, right: -80 }} />
      <div className="cs-blob" style={{ width: 280, height: 280, background: '#ffd93d', bottom: 0, left: -60 }} />

      <div className="cs-inner">
        <div className="cs-header">
          <div className="cs-eyebrow">🎭 Round Setup</div>
          <h2 className="cs-title">Pick a Category</h2>
          <p className="cs-sub">The host chooses — players won't see this screen</p>
        </div>

        <div className="cs-players-strip">
          {players.map((name, i) => (
            <div key={i} className="cs-player-pill">{name}</div>
          ))}
        </div>

        {cachedCategories.length > 0 && (
          <div className="cs-cached-section">
            <div className="cs-cached-label">⚡ Already cached — click to use</div>
            <div className="cs-cached-chips">
              {cachedCategories.map((cat, i) => (
                <button
                  key={cat}
                  className="cs-cached-chip"
                  style={{ animationDelay: `${i * 0.06}s` }}
                  onClick={() => setCategory(cat)}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        )}

        <div className="cs-card">
          <label className="cs-label">Category</label>
          <div className="cs-input-row">
            <input
              className="cs-input"
              type="text"
              placeholder="e.g. Things at a beach"
              value={category}
              onChange={e => setCategory(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleGenerate()}
              disabled={isLoading}
              autoFocus
            />
            <button
              className="cs-gen-btn"
              onClick={handleGenerate}
              disabled={isLoading || !category.trim()}
            >
              {isLoading ? <div className="cs-spinner" /> : '✨ Generate'}
            </button>
          </div>

          {source && (
            <div className={`cs-source-badge ${source}`}>
              {source === 'gemini' ? '✨ Generated by Gemini' : '⚡ Loaded from cache'}
            </div>
          )}
          {isLoading && !source && (
            <div className="cs-loading-text">Generating words for "{category}"...</div>
          )}
          {status === 'error' && (
            <div className="cs-error-msg">⚠️ {errorMsg}</div>
          )}
        </div>

        <p className="cs-hint">💡 Words will be secretly dealt to each player after this</p>
      </div>
    </div>
  );
}